# Generated by Django 4.2.5 on 2023-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_app', '0002_alter_discipline_users_favorite_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
