# Generated by Django 4.2.5 on 2023-10-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_app', '0003_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='tournaments',
            field=models.ManyToManyField(related_name='sponsors', to='torneo_app.tournament'),
        ),
    ]
