# Generated by Django 4.2.5 on 2023-10-17 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_app', '0005_alter_sponsor_tournaments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_number_of_participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='tournamentassignment',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['-applying_deadline'], name='torneo_app__applyin_46b850_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['applying_deadline'], name='torneo_app__applyin_763dc1_idx'),
        ),
    ]
