# Generated by Django 4.2.5 on 2023-10-19 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneo_app', '0006_alter_tournament_max_number_of_participants_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentassignment',
            unique_together={('tournament', 'licence_number'), ('tournament', 'player'), ('tournament', 'ranking')},
        ),
    ]
