# Generated by Django 4.2.5 on 2023-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_app', '0007_alter_tournamentassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='tournaments',
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='torneo_app.sponsor'),
        ),
    ]
