# Generated by Django 4.2.5 on 2023-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_app', '0009_tournament_is_ladder_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='lattitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
