# Generated by Django 4.2.5 on 2023-12-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_app', '0010_tournament_lattitude_tournament_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
